// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZq9UzjbMqNgxXaWtwSLh5RJN2WnZssAs',
    appId: '1:817802216512:web:137984cda35b06904c0ba5',
    messagingSenderId: '817802216512',
    projectId: 'simponclone',
    authDomain: 'simponclone.firebaseapp.com',
    storageBucket: 'simponclone.appspot.com',
    measurementId: 'G-SD829S7E5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATmE1G4CGemxr_kGlzwUMNz4rDCfw-950',
    appId: '1:817802216512:android:4963140c51140b704c0ba5',
    messagingSenderId: '817802216512',
    projectId: 'simponclone',
    storageBucket: 'simponclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLaf2Qi1thr8a2eIXJEXe8dKEae3BMGS8',
    appId: '1:817802216512:ios:14f880a9a1d316314c0ba5',
    messagingSenderId: '817802216512',
    projectId: 'simponclone',
    storageBucket: 'simponclone.appspot.com',
    iosClientId: '817802216512-g922mf6i7bkqllfj0mhti6loseqccob2.apps.googleusercontent.com',
    iosBundleId: 'com.example.simponClone',
  );
}
