// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXUK_vAq_ZDw_MScFhpQciV3Tp0ysp_MM',
    appId: '1:200447432684:web:d1807ae639be1bcfb3d2c9',
    messagingSenderId: '200447432684',
    projectId: 'simplon-app',
    authDomain: 'simplon-app.firebaseapp.com',
    storageBucket: 'simplon-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoz-0tij4yd3xwc4ETs_ASGR7rr7Il3-Q',
    appId: '1:200447432684:android:53fa0968026aedf9b3d2c9',
    messagingSenderId: '200447432684',
    projectId: 'simplon-app',
    storageBucket: 'simplon-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxiZSsAaVO7whexd-2j1UuU0zs1MxELw',
    appId: '1:200447432684:ios:1527aa56f5a69d89b3d2c9',
    messagingSenderId: '200447432684',
    projectId: 'simplon-app',
    storageBucket: 'simplon-app.appspot.com',
    iosClientId: '200447432684-3cbbv49k6o16sb5nj56qnebqv4p8jpsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.simponClone',
  );
}
